
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr  2 2026 09:21:29 IST (Apr  2 2026 03:51:29 UTC)

// Verification Directory fv/counter8 

module counter8(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16;
  SDFFRHQX1 \count_reg[7] (.RN (n_16), .CK (clk), .D (n_0), .SI
       (count[7]), .SE (n_14), .Q (count[7]));
  DFFRHQX1 \count_reg[6] (.RN (n_16), .CK (clk), .D (n_15), .Q
       (count[6]));
  OA21X1 g185__2398(.A0 (count[6]), .A1 (n_12), .B0 (n_14), .Y (n_15));
  DFFRHQX1 \count_reg[5] (.RN (n_16), .CK (clk), .D (n_13), .Q
       (count[5]));
  AOI2BB1XL g188__5107(.A0N (count[5]), .A1N (n_10), .B0 (n_12), .Y
       (n_13));
  NAND2XL g187__6260(.A (count[6]), .B (n_12), .Y (n_14));
  DFFRHQX1 \count_reg[3] (.RN (n_16), .CK (clk), .D (n_9), .Q
       (count[3]));
  AOI21XL g191__4319(.A0 (n_7), .A1 (n_8), .B0 (n_10), .Y (n_11));
  AND2X1 g190__8428(.A (count[5]), .B (n_10), .Y (n_12));
  OA21X1 g194__5526(.A0 (count[3]), .A1 (n_6), .B0 (n_8), .Y (n_9));
  NOR2XL g193__6783(.A (n_7), .B (n_8), .Y (n_10));
  NAND2XL g196__3680(.A (count[3]), .B (n_6), .Y (n_8));
  AOI21XL g197__1617(.A0 (n_4), .A1 (n_3), .B0 (n_6), .Y (n_5));
  DFFRHQX1 \count_reg[1] (.RN (n_16), .CK (clk), .D (n_2), .Q
       (count[1]));
  NOR2XL g199__2802(.A (n_4), .B (n_3), .Y (n_6));
  OA21X1 g200__1705(.A0 (count[0]), .A1 (count[1]), .B0 (n_3), .Y
       (n_2));
  NAND2XL g202__5122(.A (count[0]), .B (count[1]), .Y (n_3));
  INVXL g203(.A (count[7]), .Y (n_0));
  INVXL g207(.A (rst), .Y (n_16));
  DFFRX1 \count_reg[2] (.RN (n_16), .CK (clk), .D (n_5), .Q (count[2]),
       .QN (n_4));
  DFFRX1 \count_reg[4] (.RN (n_16), .CK (clk), .D (n_11), .Q
       (count[4]), .QN (n_7));
  DFFRX1 \count_reg[0] (.RN (n_16), .CK (clk), .D (n_1), .Q (count[0]),
       .QN (n_1));
endmodule

