
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr  2 2026 10:40:05 IST (Apr  2 2026 05:10:05 UTC)

// Verification Directory fv/mealy_1011 

module mealy_1011(clk, rst, x, y);
  input clk, rst, x;
  output y;
  wire clk, rst, x;
  wire y;
  wire [1:0] state;
  wire n_0, n_1;
  SDFFRHQX1 \state_reg[1] (.RN (n_0), .CK (clk), .D (state[0]), .SI
       (n_1), .SE (x), .Q (state[1]));
  AND3XL g140__2398(.A (x), .B (state[1]), .C (state[0]), .Y (y));
  NOR2BXL g141__5107(.AN (state[1]), .B (state[0]), .Y (n_1));
  DFFRHQX1 \state_reg[0] (.RN (n_0), .CK (clk), .D (x), .Q (state[0]));
  INVXL g143(.A (rst), .Y (n_0));
endmodule

